server:
  port: 8006
spring:
   application:
    name: springcloud-dept                                 #这个名字决定不能改。三个微服务属于同一个app
   profiles: dev
eureka:
#  server:
#    enable-self-preservation: false是否关闭eureka的保护机制
  client: #客户端注册进eureka服务列表内
    service-url:
      #单机
      defaultZone: http://localhost:7001/eureka
---
server:
  port: 8007
spring:
   application:
    name: springcloud-dept                                 #这个名字决定不能改。三个微服务属于同一个app
   profiles: test
eureka:
#  server:
#    enable-self-preservation: false是否关闭eureka的保护机制
  client: #客户端注册进eureka服务列表内
    service-url:
      #单机
      defaultZone: http://localhost:7001/eureka