server:
  port: 8081
spring:
   profiles: dev
   application:
    name: config-client                                 #这个名字决定不能改。三个微服务属于同一个app
   
eureka:
#  server:
#    enable-self-preservation: false是否关闭eureka的保护机制
  client: #客户端注册进eureka服务列表内
    service-url:
      #单机
      defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8082
spring:
   profiles: test
   application:
    name: config-client                                 #这个名字决定不能改。三个微服务属于同一个app
   
eureka:
#  server:
#    enable-self-preservation: false是否关闭eureka的保护机制
  client: #客户端注册进eureka服务列表内
    service-url:
      #单机
      defaultZone: http://localhost:8761/eureka/
