spring:
  application:
    name: springcloud-config-default
  profiles:
    active:
    - dev
---
spring:
  application:
    name: springcloud-config-dev
  profiles: dev

---
spring:
  application:
    name: springcloud-config-test
  profiles: test